<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * Pager template
 *
 * @see Mage_Page_Block_Html_Pager
 */
?>
<?php $offset = intval($this->getCollection()->getSize() - $this->getCurrentPage()); ?>
<?php $length = intval($this->getCurrentPage() + 5); ?>
<?php foreach ($this->getPages() as $_page): ?>
	<?php echo $this->getPageUrl($_page) ?>
<?php endforeach;; ?>
