<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

/**
 * This template is for generic wrapper purposes, including ajax.updater loaded blocks
 *
 * Usage in layout xml files:
 * <block type="core/template" template="page/html/wrapper.phtml">
 *    <action method="setId"><id>some-custom-identificator</id></action>
 *
 *    <!-- optional -->
 *    <action method="setTag"><tag>span</tag></action> <!-- div is used if not specified -->
 *    <action method="setParams"><params>class="custom-class"</params></action>
 *
 *    <!-- insert wrapped blocks here -->
 * </block>
 */
?>
<?php $_tag = $this->hasTag() ? $this->getTag() : "div" ?>
<<?php echo $_tag?> id="<?php echo $this->getId()?>" <?php echo $this->getParams()?>>
<?php echo $this->getChildHtml()?>
</<?php echo $_tag?>>
