<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<div id="widget-progress-opcheckout">

<?php if ($this->getCheckout()->getStepData('widget', 'complete')): ?>
<?php $completeClass = $this->getCheckout()->getStepData('widget', 'complete') ? 'complete' : ''; ?>
<dt class="<?php echo $completeClass ?>">
    <?php echo $this->__('Shipping Information') ?> <span class="changelink"><span class="separator">|</span> <a
        href="#payment"
        onclick="checkout.changeSection('opc-widget');return false;"><?php echo $this->__('Change') ?></a></span>
</dt>
<dd class="<?php echo $completeClass ?>">
    <?php if ($this->getCheckout()->getStepData('widget', 'complete')): ?>
    <address><?php echo $this->getShipping()->format('html') ?></address>
    <?php endif; ?>
</dd>
<?php else: ?>
<dt>
    <?php echo $this->__('Shipping Information') ?>
</dt>
<?php endif; ?>

</div>