<?php 
ob_start();

$order = $this->getOrder();
$customer = array(
		'fn' => $order->getBillingAddress()->getFirstname(),
		'ln' => $order->getBillingAddress()->getLastname(),
		'mn' => $order->getBillingAddress()->getMiddlename()
		);
$address = Mage::getModel('sales/order_address')->load($order->getShippingAddress()->getId());
$regionCollection = Mage::getModel('directory/region_api')->items($address['country_id']);
foreach ($regionCollection as $k=>$v) {
	if ($address['region'] == $v['name']) {
		$address['region'] = $v['code'];
	}
}
$_product = Mage::getModel('catalog/product')->load($this->getRequest()->getParam('item_id'));
$_helper = $this->helper('catalog/output');
$attributes = $_product->getAttributes();
$_items = $order->getAllItems();
$_item = null;
foreach ($_items as $item) {
	if ($_product->getId() == $item->getProductId()) {
		$_item = $item;
	}
}
$options = $_item->getProductOptions();
$optionValues = array();
if (!empty($options['options'])) {
	foreach ($options['options'] as $option) {
		
		$optionValues[$option['label']] = $option['value'];
		
		if ($option['label'] == 'Chain length') {
			$length = $option['value'];
			$default_length = floatval(Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'chainlength', 1));
			$default_weight = floatval(Mage::getResourceModel('catalog/product')->getAttributeRawValue($_product->getId(), 'peiceweight', 1));
		};
	};
}
?>

<link rel="stylesheet" href="/skin/adminhtml/default/default/jquery-ui.css">
<script src="/js/jquery/jquery-1.7.1.min.js"></script>
<script src="/js/html2canvas.js"></script>
<script src="/js/jquery-ui.js"></script>
<style>
body { margin: 0px; }
.wrapper {
	position: relative;
	width: 900px;
	height: 1120px;
    color: #15256c;
}
.background {
	position: absolute;
	top: 0px;
	left: 0px;
}
.logo {
	position: absolute;
	top: 97px;
	left: 110px;
}
.text-address {
	position: absolute;
	right: 27px;
	top: 132px;
	text-align: right;
	font-size: 24px;
	line-height: 23px;
}
.text-order {
	position: absolute;
	top: 186px;
	left: 83px;
	text-align: left;
	width: 817px;
	font-size: 26px;
	line-height: 22px;
}
.photo {
	width: 300px;
	font-size: 13px;
	text-align: center;
	height: 301px;
	border-right: 1px solid black;
	border-top: 1px solid black;
}
.photo > img {
	background-color: white;
	border-right: 1px solid #C0C0C0;
	border-top: 1px solid #C0C0C0;
	width: 299px;
}
.customer {
	font-size: 29px;
	line-height: 42px;
	width: 492px;
	margin-left: 25px;
	margin-top: -7px;
}
.product {
	position: absolute;
	top: 487px;
	left: 83px;
	width: 817px;
	height: 710px;
}
.specs {
	position: absolute;
	top: 0px;
	left: 0px;
	border: 0px none;
	width: 817px;
}
.specs-table {
	width: 818px;
	border-collapse: collapse;
	margin-left: 82px;
}
.specs-table tr {
    border-bottom: 1px solid #c4c1bc;
}
.specs-table tr:nth-child(even) {
	background: #eeeded;
}
.specs-table tr:nth-child(odd) {
	background: #ffffff;
}
.specs-table tr th {
    font-weight: bold;
    font: 8px Verdana;
    text-align: left;
    padding-left: 6px;
}
.specs-table tr td {
	padding: 2px 0px 1px 6px;
	font: 25px Verdana;
	color: #666;
	border-left: 1px solid #c4c1bc;
	height: 38px;
	padding-left: 16px;
	width: 50%;
}
.specs-table tr td:n-thchild(odd) {
	border-right: 0;
}
.prodname {
	height: 166px;
	padding-left: 14px;
	font-size: 33px;
	line-height: 1.3em;
	overflow: hidden;
}
.sign {
	text-align: center;
	width: 462px;
	margin-left: 32px;
	margin-top: 5px;
}
.sign .susan {
	margin-top: 14px;
	font-size: 26px;
}
.sign .replvalue {
	color: #a80007;
	font-size: 33px;
	margin-top: 12px;
}
#editData {
	position: absolute;
	top:10px;
	right: 10px;
	border-width: 1px;
    border-style: solid;
    border-color: #ed6502 #a04300 #a04300 #ed6502;
    padding: 1px 7px 2px 7px;
	background: #ffac47 url(/skin/adminhtml/default/default/images/btn_bg.gif) repeat-x 0 100%;
    color: #fff;
    font: bold 12px arial, helvetica, sans-serif;
    cursor: pointer;
    text-align: center !important;
    white-space: nowrap;
}
#editData span {
	line-height: 1.35em;
    background-repeat: no-repeat;
    background-position: 0 50%;
}
#editData span span {
    background: none !important;
    padding: 0 !important;
    margin: 0 !important;
    display: inline !important;
}
#dialog-form form p label {
	min-width: 140px;
    display: inline-block;
}
@media print {
	#editData {
		display: none;
	}
}
</style>

<body>

<img src="<?php echo $this->getSkinUrl('images/miniappr_bg.jpg') ?>" class="background">

<div class="wrapper">
	
	<table cellspacing="0" cellpadding="0" border="0" style="margin-left: 82px;margin-top: 96px;width: 818px;"><tbody>
		<tr>
			<td style="width: 433px; text-align: center;">
				<img src="<?php echo $this->getSkinUrl('images/miniappr_logo.png') ?>" style="margin-left: 6px">
			</td>
			<td style="vertical-align: bottom; font-size: 24px;">
				28w 47th st - New York, NY 100036
			</td>
		</tr>
	</tbody></table>
	
	<table cellspacing="0" cellpadding="0" border="0" style="margin-left: 82px;margin-top: 29px;width: 818px;"><tbody>
		<tr>
			<td style="width: 301px;">
				<div class="photo">
					<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(300, 300)->setQuality(85); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
				</div>
			</td>
			<td style="vertical-align: top;">
				<div class="customer">
					Certificate #<?php echo $order->getIncrementId();?><br>
					<?php echo implode(" ", $customer) ?><br>
					<?php echo nl2br($address['street']) . "<br>" . $address['city'] . ", " . $address['region'] . '<br>' . $address['postcode']?><br>
				</div>
			</td>
		</tr>
	</tbody></table>

	<div style="height: 464px; overflow: hidden;">
		<table cellspacing="0" class="specs-table"><tbody>
		<?php 
		$i = 0;
		$formData = array();
		foreach ($attributes as $attribute) {
			if ($attribute->getIsVisibleOnFront() && !in_array($attribute->getAttributeCode())) {
				$value = $attribute->getFrontend()->getValue($_product);
		
				if (!$_product->hasData($attribute->getAttributeCode())) {
					$value = Mage::helper('catalog')->__('N/A');
				} elseif ((string)$value == '') {
					$value = Mage::helper('catalog')->__('No');
				} elseif ($attribute->getFrontendInput() == 'price' && is_string($value)) {
					$value = Mage::app()->getStore()->convertPrice($value, true);
				}
		
				if (is_string($value) && strlen($value) && $value!='No' && $i<=10) {
					$i++;
		?>
					<tr <?php if ($i == 1)	echo 'style="border-top: 1px solid #c4c1bc;"'?> id="attr<?php echo $i; ?>">
						<td style="border-left: 0 none;"><b><?php echo $this->htmlEscape($this->__($attribute->getStoreLabel())) ?></b></td>
						<td>
							<?php if(!empty($length) && $this->htmlEscape($this->__($attribute->getStoreLabel())) == 'Chain Length'): ?>
								<?php echo $length . ' inches' ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>$length . ' inches'); ?>
							<?php elseif(!empty($length) && $this->htmlEscape($this->__($attribute->getStoreLabel())) == 'Item Weight'): ?>
								<?php // Math.round(( (dto / dfrom) * sV) * 10 )/10; ?>
								<?php echo round( ($default_weight / $default_length * $length), 1) . ' grams'; ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>round( ($default_weight / $default_length * $length), 1) . ' grams'); ?>
							<?php elseif(array_key_exists($attribute->getStoreLabel(), $optionValues)):?>
								<?php echo $optionValues[$attribute->getStoreLabel()]; ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>$optionValues[$attribute->getStoreLabel()]); ?>
								<?php unset($optionValues[$attribute->getStoreLabel()]); ?>
							<?php else: ?>
								<?php echo $_helper->productAttribute($_product, $value, $attribute->getAttributeCode()); ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>$_helper->productAttribute($_product, $value, $attribute->getAttributeCode())); ?>
							<?php endif; ?>
						</td>
					</tr>
		<?php 
				}
			}
		}
		if( !empty( $optionValues ) && $i<=10 ) {
			foreach ($optionValues as $label => $value) {
				$i++;
				if($i<=10) {
		?>
					<tr <?php if ($i == 1)	echo 'style="border-top: 1px solid #c4c1bc;"'?> id="attr<?php echo $i; ?>">
						<td style="border-left: 0 none;"><b><?php echo $label ?></b></td>
						<td>
							<?php if(!empty($length) && $label == 'Chain Length'): ?>
								<?php echo $length . ' inches' ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>$length . ' inches'); ?>
							<?php elseif(!empty($length) && $label == 'Item Weight'): ?>
								<?php // Math.round(( (dto / dfrom) * sV) * 10 )/10; ?>
								<?php echo round( ($default_weight / $default_length * $length), 1) . ' grams'; ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>round( ($default_weight / $default_length * $length), 1) . ' grams'); ?>
							<?php else: ?>
								<?php echo $value; ?>
								<?php $formData['attr'.$i] = array('label'=>$this->htmlEscape($this->__($attribute->getStoreLabel())),'value'=>$value); ?>
							<?php endif; ?>
						</td>
					</tr>
		
		<?php 		
				}
				
			}
		}
		?>
		</tbody></table>
	</div>

	<table cellspacing="0" cellpadding="0" border="0" style="margin-left: 82px; width: 818px; height: 234px;"><tbody>
		<tr>
			<td style="width: 324px;">
				<div class="prodname">
		            <?php echo $this->htmlEscape($_product->getName()) ?>
				</div>
			</td>
			<td>
				<div class="sign">
					<img src="<?php echo $this->getSkinUrl('images/miniappr_sign.png') ?>">
					<div class="susan">Susan H. Arnold &ndash; Certified Gemologist</div>
					<div class="replvalue">Replacement Value : 
					<?php
						$price = Mage::helper('core')->currency($_product->getPrice(),true,false);
						if (substr($price, -3) == '.00')
							$price = substr($price, 0, -3);
						echo $price;
					?></div>
				</div>
			</td>
		</tr>
	</tbody></table>
    
</div>
<div id="dialog-form" title="Modify appraisal data">
	<form>
		<?php foreach ($formData as $id => $row): ?>
      		<p>
	      		<label for="f<?php echo $id; ?>"><small><?php echo $row['label']?></small></label>
	      		<input type="text" name="<?php echo $id; ?>" id="f<?php echo $id; ?>" size="10" value="<?php echo $row['value']?>" style="font-size: 12px; padding: 3px 5px;" class="text ui-widget-content ui-corner-all">
      		</p>
 		<?php endforeach; ?>
      	<!-- Allow form submission with keyboard without duplicating the dialog button -->
		<input type="submit" tabindex="-1" style="position:absolute; top:-1000px">
	</form>
</div>
<img id="canvasImg" />

</body>
<?php 
	$html = ob_get_contents();
	ob_end_clean();

	echo $html;
?>
<script>
html2canvas(document.body, {
	width: 900,
	height: 1200,
	onrendered: function(canvas) {
		var dataURL = canvas.toDataURL();
		document.getElementById('canvasImg').src = dataURL;
		$('.wrapper, .background').hide();
	}
});
$(function(){
	var dialog, form;

  	function updateData() {

		$("#dialog-form input[type=text]").each(function(){
			var input = $(this).attr('id').substring(1);
			var value = $(this).val();

			console.log(input,value);
			$("#"+input).find('td:eq(1)').html(value);
			$("#f"+input).attr('value', value);
		});

		dialog.dialog( "close" );

		$('#canvasImg').attr('src');
		$('.wrapper, .background').show();
		
		html2canvas(document.body, {
			width: 900,
			height: 1200,
			onrendered: function(canvas) {
				var dataURL = canvas.toDataURL();
				document.getElementById('canvasImg').src = dataURL;
				$('.wrapper, .background').hide();
			}
		});
  	}

  	dialog = $( "#dialog-form" ).dialog({
	    autoOpen: false,
	    height: 400,
	    width: 350,
	    modal: true,
	    buttons: {
      		"Update data": updateData,
      		Cancel: function() {
        		dialog.dialog( "close" );
      		}
		},
    	close: function() {
//       		form[ 0 ].reset();
    	}
  	});

  	form = dialog.find( "form" ).on( "submit", function( event ) {
    	event.preventDefault();
    	updateData();
  	});

  	$('<button id="editData" title="Edit Appraisal"><span><span><span>Edit Appraisal</span></span></span></button>').prependTo(document.body);
	$('body').on('click', '#editData', function() {
		dialog.dialog( "open" );
	});

});
</script>