<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div>
    <ul class="cart-links">
        <li class="first"><a class="button grey left" href="<?php echo $this->getData('back_link') ? $this->getUrl($this->getData('back_link')) :  $this->getUrl('')."#cart"; ?>"  title="<?php echo $this->__('Back'); ?>" ><?php echo $this->__('Back'); ?></a></li>
        <li class="title"><h1><?php echo $this->__($this->getTitle()); ?></h1></li>
    </ul>
    <div class="clear"></div>
</div>