<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */

Mage::helper('awmobile')->prepareCartMessages();

?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<h1 class="shopping-cart-h1"><?php echo $this->__('Avianne &amp; Co. Secure Checkout'); ?></h1>
<form id="cart-form" action="" method="post" class="cart-update-form-data">
<div class="cart-items-list">
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
        <?php $renderer = $this->getItemRenderer($_item->getProductType())->setItem($_item); $deleteUrl =  $renderer->getDeleteUrl(); ?>
    <?php endforeach ?>
</div>
</form>
<div class="cart-order-info">
	<h4><?php echo $this->__('Order Information'); ?></h4>
	<?php echo $this->getChildHtml('coupon') ?>
	<div class="clear"></div>
	<?php echo $this->getChildHtml('totals'); ?>
	<?php if (Mage::getStoreConfig('checkout/options/onepage_checkout_enabled') || !Mage::getStoreConfig('checkout/options/onepage_checkout_disabled')): ?>
    	<a id="checkout-button" class="button button-blue-gradient checkout back" href="<?php echo $this->getUrl('checkout'); ?>" title="<?php echo $this->__('Checkout'); ?>" <?php if($isCartEmpty):?>style="display:none;"<?php endif;?>><span class="nowrap"><?php echo $this->__('Checkout'); ?></span></a>
	<?php endif; ?>
</div>

<script type="text/javascript">
    $j(document).ready(function(e){
        mobileCart.registerSubmit('cart-form', '<?php echo $this->getUrl('awmobile/cart/updatePost') ?>');
        mobileCart.contentUrl = '<?php echo $this->getUrl('awmobile/cart/content'); ?>';
    });
</script>
<div class="clear"></div>
<?php echo $this->getChildHtml('giftcards') ?>
<div class="clear"></div>

<?php /*?>
<ul class="mobile-drop-down alt-paymemts">
	<li class="parent-item parent-item-1 inactive">
		<a href="#"><span class="item-1"><?php echo $this->__('Would you like to select an alternate payment method'); ?></span></a>
	</li>
	<li class="child-item child-item-1">
		<div class="payment-methods">
			<ul class="alt-payment-methods">
				<li class="item-1"><?php echo $this->getChildHtml('paypal_checkout_button'); ?></li>
				<li class="item-2"><?php echo $this->getChildHtml('google_checkout_button'); ?></li>
				<li class="item-3"><?php echo $this->getChildHtml('amazon_checkout_button'); ?></li>
			</ul>
		</div>
	</li>
</ul>
<?php */?>
<?php /*if(!$this->hasError()): ?>
<div class="p-methods">
    <ul class="checkout-types">
        <?php if($this->getMethods('methods')): ?>
        	<?php $i = 1; ?>
            <?php foreach ($this->getMethods('methods') as $method): ?>
                <?php if ($methodHtml = $this->getMethodHtml($method)): ?>
                <li class="item-<?php echo $i?>"><?php echo $methodHtml; ?></li>
                <?php endif; ?>
                <?php $i++; ?>
            <?php endforeach; ?>
        <?php else:?>
                <?php echo $this->getChildHtml('methods') ?>

        <?php endif; ?>
    </ul>
</div>
<?php endif; */?>
<script type="text/javascript">
	function editCartItem(id) {
		var edbtn = jQuery('#'+id).find('.edit-cart');
		if(edbtn.hasClass('active')) {
			/*edbtn.removeClass('active').html('<?php echo $this->__('Edit'); ?>');
			jQuery('#'+id).find('.edit-input-box').hide().end().find('.normal-input-box').show();*/
			jQuery('#cart-form').submit();
		} else {
			edbtn.addClass('active').html('<?php echo $this->__('Save'); ?>');
			jQuery('#'+id).find('.normal-input-box').hide().end().find('.edit-input-box').show();
		}
	}
	function removeCartItem(id) {
		var box = jQuery('#'+id).find('.edit-input-box input');
		var val = box.val();
		if( val > 1 ) {
			box.val( val-1 );
			jQuery('#cart-form').submit();
			return false;
		} else {
			mobileCart.deleteItem('<?php echo $this->getBaseUrl('web'); ?>awmobile/cart/delete/id/'+id+'/'); 
			return false;
		}
	}
</script>