<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php if ($footerLinksHtml = Mage::helper('awmobile')->getCustomFooterLinksHtml()): ?>
    <?php echo $footerLinksHtml; ?>
<?php else: ?>
    <?php $_links = $this->getLinks(); ?>
    <?php if(count($_links)>0): ?>
        <div<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?> class="foooter_menu">
            <?php foreach($_links as $_link): ?>
                <span <?php if($_link->getIsFirst()): ?> class="item first"<?php elseif($_link->getIsLast()): ?> class="item last"<?php else: ?> class="item"<?php endif; ?><?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?><a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?><?php echo $_link->getAfterText() ?></a></span>
                <?php if(!$_link->getIsLast()): ?><span class="sep">|</span><?php endif; ?>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
<?php endif; ?>
