<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
/**
 * @var $this Mage_Tax_Block_Checkout_Grandtotal
 * @see Mage_Tax_Block_Checkout_Grandtotal
 */
?>
<?php if ($this->includeTax() && $this->getTotalExclTax()>=0):?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Excl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
    </td>
</tr>
<?php echo $this->renderTotals('taxes', $this->getColspan()); ?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->helper('tax')->__('Grand Total Incl. Tax')?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
        <strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
    </td>
</tr>
<?php else:?>
<tr>
    <td style="<?php echo $this->getStyle() ?>" class="a-right" colspan="<?php echo $this->getColspan(); ?>">
        <strong><?php echo $this->getTotal()->getTitle() ?></strong>
    </td>
    <td style="<?php echo $this->getStyle() ?>" class="a-right">
    	<?php if($this->getRequest()->getModuleName()=='ixcba' && $this->getRequest()->getControllerName()=='checkout_onepage'): ?>
        	<strong><?php echo $this->helper('checkout')->formatPrice($this->getTotal()->getValue()) ?></strong>
        <?php else: ?>
        	<strong><?php echo $this->helper('checkout')->formatPrice($this->getTotalExclTax()) ?></strong>
        <?php endif; ?>
    </td>
</tr>
<?php endif;?>
