<?php
/**
 * Category layered navigation
 *
 * @see Mage_Catalog_Block_Layer_View
 */
?>
<?php $currentCategory = Mage::registry("current_category"); ?>
<?php $cat_replace_arr = array(74,76,149,256,260,285,312); ?>
<?php if ($currentCategory->getDisplayMode()!=Mage_Catalog_Model_Category::DM_PAGE || isset($_GET['view-all'])): ?>
	<?php if($this->canShowBlock()): ?>
				<?php $_filters = $this->getActiveFilters(); ?>
			    <?php foreach ($_filters as $_filter): ?>
			    	<?php $activeFilters[trim($_filter->getLabel())] = $this->__($_filter->getName()); ?>
			    <?php endforeach; ?>
		        <?php if($this->canShowOptions()): ?>
					<?php $_filters = $this->getFilters() ?>
					<?php foreach ($_filters as $_filter): ?>
						<?php if($_filter->getItemsCount()): ?>
							<?php if($_filter->getName()=="Metal Type" && in_array($currentCategory->getId(), $cat_replace_arr)): ?>
								<?php continue; ?>
							<?php elseif($_filter->getName()=="Diamond Color" && !in_array($currentCategory->getId(), $cat_replace_arr)): ?>
								<?php continue; ?>
							<?php endif;?>
							<?php if($_filter->getName()!="Category" && $_filter->getName()!="Price"): ?>
								<!-- <td class="narrow-by <?php echo str_replace(" ", "_", strtolower($_filter->getName())); ?>"> -->
								<div class="narrow-by <?php echo str_replace(" ", "_", strtolower($_filter->getName())); ?>">
									<?php $buff = '<dl id="narrow-by-list"><dt class="filter-label"><select name="'.$this->__($_filter->getName()).'"><option>'.$this->__($_filter->getName()).'</option></select><span>&nbsp;</span></dt>'; ?>
									<?php $active = array_keys($activeFilters,$_filter->getName()); ?>
									<?php $buff.= '<dd class="filter-dropdown">'.$_filter->getHtml().'</dd></dl>'; ?> 
									<?php echo $buff ?>			
								</div>
								<!-- </td>     -->
							<?php elseif($_filter->getName()=="Price"): ?>
								<!-- <td class="filter-price"> -->
								<div class="filter-price">
									<dl class="price-box">
										<?php /* <dd class="filter-dropdown"><?php echo str_replace('Search', 'SHOW ITEMS ('.$totalNum.')', $_filter->getHtml()) ?></dd> */ ?>
										<dd class="filter-dropdown"><?php echo $_filter->getHtml(); ?></dd>
										<dt class="filter-label"><?php echo $this->__($_filter->getName()) ?></dt>
									</dl>
								</div>
								<!-- </td>      -->
							<?php endif; ?>  
						<?php endif; ?>
					<?php endforeach; ?>
				<?php endif; ?>
	<?php endif; ?>
<?php endif; ?>