<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>


<img src="https://images-na.ssl-images-amazon.com/images/G/01/Iris3_US/en_US/inca/images/37x23-whitegrad-x1-TEMP.png" width"37" height="23">

<!--
<img src="https://images-na.ssl-images-amazon.com/images/G/01/lwa/btnLWA_gold_32x32.png" height="23">
-->

<?php print $this->__('Login and Pay with Amazon'); ?>
