<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php if ($this->isEnabled() && !$this->isLoaded()) : ?>

<script async='async' type='text/javascript' src='<?php echo $this->getWidgetsUrl(); ?>'></script>

<?php endif; ?>