<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Points
 * @copyright  Copyright (c) 2008-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if ($this->getTotal()->getValue()): ?>
    <tr>    
        <td class="a-right" colspan="<?php echo $this->getColspan(); ?>">
            <?php echo $this->getTotal()->getTitle(); ?>
        </td>
        <td class="a-right">
            <?php echo Mage::helper('checkout')->formatPrice($this->getTotal()->getValue()) ?>
        </td>
    </tr>
<?php endif; ?>
