<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if($pageData->getPageMetaKeywords()): ?>
<meta name="keywords" content="<?php echo $pageData->getPageMetaKeywords() ?>" />
<?php endif; ?>
<?php if($pageData->getPageMetaDescription()): ?>
<meta name="description" content="<?php echo $pageData->getPageMetaDescription() ?>" />
<?php endif; ?>
