<?php
/**
 * @category    Fishpig
 * @package     Fishpig_Wordpress
 * @license     http://fishpig.co.uk/license.txt
 * @author      Ben Tideswell <help@fishpig.co.uk>
 */
?>
<?php $page = $this->getPage() ?>
<?php if ($page->getId() == 61): ?>
	<?php /* ?>
	<link rel='stylesheet' id='uds-billboard-css' href='<?php echo $this->getSkinUrl('css/billboard.min.css') ?>' type='text/css' media='screen' />
	<div class="page-template-slider-php">
		<?php echo file_get_contents('http://www.avianneandco.com/wp/celebrities.php'); ?>
	</div>
	<script type='text/javascript' src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_JS);?>avianne/blog/billboard.min.js'></script>
	<?php */ ?>
	<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('home/celebrity.phtml')->toHtml(); ?>
<?php else: ?>
	<?php if ($page): ?>
		<?php $helper = $this->helper('wordpress') ?>
		<?php $author = $page->getAuthor() ?>
		<div class="page-title page-template-slider-php">
			<h1><?php echo $this->escapeHtml($page->getPostTitle()) ?></h1>
		</div>
		<div class="post-view">
			<div class="entry std">
				<?php if ($page->isViewableForVisitor()): ?>
					<?php if ($featuredImage = $page->getFeaturedImage()): ?>
						<div class="featured-image left"><img src="<?php echo $featuredImage->getAvailableImage() ?>" alt=""/></div>
					<?php endif; ?>
					<?php echo $page->getPostContent() ?>
					<br style="clear:both;"/>
				<?php else: ?>
					<?php echo $this->getPasswordProtectHtml() ?>
				<?php endif; ?>
			</div>
			<?php //echo $this->getCommentsHtml() ?>
		</div>
	<?php endif; ?>
<?php endif; ?>
