<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * Template for Mage_Page_Block_Html
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <?php echo $this->getChildHtml('head') ?>
</head>
    <body home="index.php" class="<?php echo $this->getBodyClass(); ?> mage-iphone<?php if (Mage::registry(AW_Mobile_Block_Catalog_Navigation::IS_NAVIGATION_PAGE)) echo " navpage"; ?>">
    <?php echo $this->getChildHtml('after_body_start') ?>
    <?php echo $this->getChildHtml('global_notices') ?>
    <div class="header">
        <?php echo $this->getChildHtml('header') ?>
    </div>
    	<div class="shop-access">
            <?php //echo $this->getChildHtml('awTopLinks') ?>

            <form id="search_mini_form" name="search_mini_form" action="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB); ?>catalogsearch/result/" method="get">
            	<div class="search-line">
            		<a id="main-nav-button" class="menu-btn inactive"><span>Menu </span></a>
	            	<div class="search-string">
	            		<div class="sub-search-button">
		            		<input id="search" type="text" name="q" value="Enter Keyword..." autocapitalize onfocus="if(this.value=='Enter Keyword...'){this.value=''}" onblur="if(this.value==''){this.value='Enter Keyword...'}" />
		            	</div>
	            	</div>
	            	<div class="search-button">
	            		<input type="submit" class="search-btn" value="" />
	            	</div>
            	</div>
			    <input type="hidden" name="order" value="relevance">
				<input type="hidden" name="dir" value="desc">
            	<div class="clear"></div>
            </form>
            	<ul class="nav mobile-drop-down">
					<li class="parent-item parent-item-1 inactive">
						<span class="item-1">Men's</span>
					</li>
					<li class="child-item child-item-1">
						<ul>
							<li class="item-1-1"><a href="/mens-diamond-rings-1">Diamond Rings</a></li>
							<li class="item-1-2"><a href="/mens-diamond-bracelets-1">Diamond Bracelets</a></li>
							<li class="item-1-3"><a href="/mens-diamond-earrings-1">Diamond Earrings</a></li>
							<li class="item-1-4"><a href="/mens-diamond-pendants-1">Diamond Pendants</a></li>
							<li class="item-1-5"><a href="/mens-diamond-chains-1">Diamond Chains</a></li>
							<li class="item-1-6"><a href="/bling-hip-hop-diamond-jewelry">Hip Hop Jewelry</a></li>
							<li class="item-1-7"><a href="/mens-solid-gold-jewelry">Solid Gold Jewelry</a></li>
							<li class="item-1-8"><a href="/diamond-cufflinks">Diamond Cufflinks</a></li>
              <li class="item-1-10"><a href="/mens-apparel">Mens Apparel</a></li>
						</ul>
					</li>
					<li class="parent-item parent-item-2 inactive">
						<span class="item-2">Women's</span>
					</li>
					<li class="child-item child-item-2">
						<ul>
							<li class="item-2-1"><a href="/womens-diamond-rings-1">Diamond Rings</a></li>
							<li class="item-2-2"><a href="/womens-diamond-bracelets-1">Diamond Bracelets</a></li>
							<li class="item-2-3"><a href="/womens-diamond-earrings-1">Diamond Earrings</a></li>
							<li class="item-2-4"><a href="/womens-diamond-pendants-1">Diamond Pendants</a></li>
							<li class="item-2-5"><a href="/womens-diamond-necklaces">Diamond Chains</a></li>
							<li class="item-2-6"><a href="/diamond-pearl-jewelry">Pearl Jewelry</a></li>
							<li class="item-2-7"><a href="/womens-silver-jewelry">Silver Jewelry</a></li>
							<li class="item-2-8"><a href="/high-end-designer-jewelry">High End Jewelry</a></li>
							<li class="item-2-9"><a href="/gemstone-jewelry">Gemstone Jewelry</a></li>
							<li class="item-2-10"><a href="/womens-gold-jewelry">Solid Gold Jewelry</a></li>
              <li class="item-2-12"><a href="/womens-apparel">Womens Apparel</a></li>
						</ul>
					</li>
					<li class="parent-item parent-item-3 inactive">
						<span class="item-3">Bridal</span>
					</li>
					<li class="child-item child-item-3">
						<ul>
							<li class="item-3-1"><a href="/diamond-wedding-rings">Wedding Rings</a></li>
							<li class="item-3-2"><a href="/diamond-anniversary-rings">Anniversary Rings</a></li>
							<li class="item-3-3"><a href="/pre-set-diamond-engagement-rings">Engagement Rings</a></li>
						</ul>
					</li>
					<li class="parent-item parent-item-4 inactive">
						<span class="item-4">Watches</span>
					</li>
					<li class="child-item child-item-4">
						<ul>
							<li class="item-4-1"><a href="/mens-diamond-watches">Mens Diamond Watches</a></li>
							<li class="item-4-2"><a href="/womens-diamond-watches">Womens Diamond Watches</a></li>
							<li class="item-4-3"><a href="/mens-luxury-wrist-watches">Mens Luxury Watches</a></li>
							<li class="item-4-4"><a href="/womens-luxury-watches">Womens Luxury Watches</a></li>
							<li class="item-4-5"><a href="/watch-accessories">Watch Accessories</a></li>
						</ul>
					</li>
					<li><a class="item-6" href="/custom-jewelry">Custom Jewelry</a></li>
				</ul>
            <div class="clear"></div>
        </div>
    <div class="content-container active">
        <div class="middle-container">
            <div class="middle col-1-layout">

            	<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('mobile_banner')->toHtml() ?>

                <div><?php echo $this->getChildHtml('breadcrumbs') ?></div>
                <div><?php echo $this->getChildHtml('messages') ?></div>
                    <div class="clear"></div>

                <div class="clear"></div>
                <div id="main" class="col-main<?php if ($this->getChild('content') && $this->getChild('content')->getIsCms() && !Mage::registry(AW_Mobile_Block_Catalog_Navigation::IS_NAVIGATION_PAGE)){ echo " is_cms"; } ?>">
                    <?php /* ?>
                    <h3 class="topbanner"><?php echo $this->__('Save 20% on Black Friday with promo code BLK223'); ?></h3>
                    <h3 class="topbanner"><?php echo $this->__('Extended returns until January 10th'); ?></h3>
                    <?php */ ?>

                    <?php if( $this->getChild('content') && $this->getChild('content')->getIsCms() && Mage::getBlockSingleton('cms/page')->getPage()->getIdentifier()=='customer-service' ): ?>
						<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('customer-services')->toHtml(); ?>
                    <?php else: ?>
                    	<?php echo $this->getChildHtml('content') ?>
                    <?php endif; ?>
                </div>
            </div>
        </div>
    </div>
    <div class="cart-container hidden">
        <div class="middle-container">
            <div class="middle col-1-layout">
                <div id="main-cart" class="col-main cart">
                    <?php echo $this->getChildHtml('cartContent') ?>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-container" id="footer-container">
        <div class="footer">
            <?php echo $this->getChildHtml('footer') ?>
        </div>
    </div>
    <?php echo $this->getChildHtml('before_body_end') ?>
    <?php echo $this->getAbsoluteFooter() ?>
</body>
</html>
