<?php
/**
 * Amazon Payments
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>

<?php if ($this->isEnableProductPayments()) : ?>

<div id="<?php echo $this->getAmazonPayButtonId(); ?>"></div>
<script type="text/javascript">
  var authRequest;

  AmazonPaymentsCallbacks["<?php echo $this->getAmazonPayButtonId(); ?>"] = function() {

      var AmazonButtonOptions = {
          type: "<?php echo ($this->isAmazonLoginEnabled()) ? 'LwA' : $this->getButtonType(); ?>",
          color: "<?php echo $this->getButtonColor(); ?>",
          size: "<?php echo $this->getButtonSize(); ?>",
          <?php if ($this->getLanguage()) : ?>
          language: "<?php echo $this->getLanguage(); ?>",
          <?php endif; ?>
          authorization: function() {
              loginOptions = {
                  scope: "profile payments:widget payments:shipping_address<?php print $this->getAdditionalScope(); ?>",
                    response_type: 'token',
                    popup: <?php print $this->isPopup(); ?>
              };

              authRequest = amazon.Login.authorize (loginOptions, "<?php echo (!$this->isPopup()) ? $this->getLoginAuthUrl() : $this->getCheckoutUrl(); ?>");
          },
          <?php if ($this->isTokenEnabled()) : ?>
          agreementType: 'BillingAgreement',
          onSignIn: function (billingAgreement) {
              amazonBillingAgreementId = billingAgreement.getAmazonBillingAgreementId();
              Mage.Cookies.set("amazonBillingAgreementId", amazonBillingAgreementId);
          },
          <?php endif; ?>
          onError: function(error) {
              console.log(error);
          }
      };

      OffAmazonPayments.Button("<?php echo $this->getAmazonPayButtonId(); ?>", "<?php echo $this->getSellerId(); ?>", AmazonButtonOptions);
  };

</script>


<br />
<p><strong>- <?php echo $this->__('OR'); ?> -</strong></p>
<br />

<?php endif; ?>
