<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="search-form" id="topSearch" style="display:none;">
    <div class="search-form-cont">
        <div class="col2-set">
            <form id="search_mini_form" name="search_mini_form" action="<?php echo $this->helper('catalogsearch')->getResultUrl() ?>" method="get">
            <div class="col-1 search-md">
                <div class="search-st"><div class="search-end">
                    <input  id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogsearch')->getQueryParamName() ?>" value="<?php echo $this->helper('catalogsearch')->getEscapedQueryText() ?>" autocapitalize />
                </div></div>
            </div>
            <div class="col-2">
                <a class="search-close" href="javascript:void(0);" onclick="hideSearchForm(); return false;">&nbsp;</a>
            </div><div class="clear"></div>
		    <input type="hidden" name="order" value="relevance">
			<input type="hidden" name="dir" value="desc">
            </form>
        </div>
    </div>
    
</div>
<div class="search-overlay" id="topSearchOverlay">
    <div class="cart-loader">
        <span>
            <img src="<?php echo $this->getSkinUrl('images/cart-ajax-loader.gif'); ?>" alt="<?php echo $this->__('Loading...'); ?>" />
        </span>
    </div>    
    
</div>

