<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="page-head">
    <h3><?php echo $this->__('Popular Search Terms') ?></h3>
</div>
<?php if( sizeof($this->getTerms()) > 0 ): ?>
<div class="box base-mini mini-product-tags">
    <div class="content">
    <ul class="bare-list">
        <?php foreach ($this->getTerms() as $_term): ?>
            <li><a href="<?php echo $this->getSearchUrl($_term) ?>" style="font-size:<?php echo $_term->getRatio()*70+75 ?>%;"><?php echo $this->htmlEscape($_term->getName()) ?></a></li>
        <?php endforeach; ?>
    </ul>
    </div>
</div>
<?php else: ?>
    <div class="note-msg">
        <?php echo $this->__('There are no search terms available.'); ?>
    </div>
<?php endif ?>
