<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<div class="note-msg">
    <?php echo $this->__('There are no products matching the selection.') ?>
</div>
<?php else: ?>
<?php // List mode ?>
<?php $_iterator = 0; ?>
<div class="upper-toolbar">
	<?php echo $this->getToolbarHtml() ?>
</div>
<?php if($this->getMode()!='grid'): ?>
<div class="listing-type-list catalog-listing">
<ul class="c-list" id="c-list">
<?php foreach ($_productCollection as $_product): ?>
    <li>
        <div class="col2-alt-set" onclick="document.location = '<?php echo $_product->getProductUrl() ?>'; return false;">
            <div class="col-1">
                <?php // Product Image ?>
                <div class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(150, 150); ?>" width="150" height="150" alt="<?php echo $this->helper('awmobile')->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->helper('awmobile')->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </div>
            </div>
            <div class="col-2 aranged">
                <?php // Product description ?>
                <div class="product-shop">
                    <?php $simplePricesTax = ($this->helper('tax')->displayPriceIncludingTax() || $this->helper('tax')->displayBothPrices()); ?>
                    <?php $_minimalPriceValue = $_product->getMinimalPrice() ?>
                    <?php $_minimalPrice = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $simplePricesTax) ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->helper('awmobile')->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    <?php
                    if ($_product->getTypeId() == 'bundle'){
                        list($_minimalPrice, $_maximalPrice) = $_product->getPriceModel()->getPrices($_product);
                        $_price = $_minimalPrice;
                    } elseif ($_product->getTypeId() == 'grouped') {     
                        $_exclTax = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $includingTax = null);
                        $_inclTax = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $includingTax = true);                        
                        $_price = $_inclTax;
                        if (!$this->helper('tax')->displayPriceIncludingTax()) {
                            $_price = $_exclTax;
                        }                        
                    } else {
                        $_price = $_product->getFinalPrice();
                    } /*?>
                    <span class="product-price"><?php if(!in_array(99, $_product->getCategoryIds())) {echo Mage::app()->getStore()->convertPrice( $_price, true );} else { echo "Please Call For Price"; } ?></span>
                    <?php */ ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>
                <?php /* ?>
                <div class="description vert">
                    <?php $_descr = $this->helper('catalog/output')->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                        if (strlen($_descr) > 77){
                            $_descr = substr($_descr, 0, 77)."...";
                        }
                        echo $this->helper('awmobile')->stripTags($_descr); ?>
                </div>
                <div class="description hor">
                    <?php $_descr = $this->helper('catalog/output')->productAttribute($_product, $_product->getShortDescription(), 'short_description');
                        if (strlen($_descr) > 122){
                            $_descr = substr($_descr, 0, 122)."...";
                        }
                        echo $this->helper('awmobile')->stripTags($_descr); ?>
                </div>
                <?php */ ?>
            </div>
            <div class="clear"></div>
    </div>
</li>
<?php endforeach; ?>
</ul>
</div>
<?php else: ?>
<div class="listing-type-grid catalog-listing">
<div class="c-list" id="c-list">
<?php $i = 0;?>
<div class="grid-row">
<?php foreach ($_productCollection as $_product): ?>
	<?php if($i%2==0&&$i!=0):?>
    	</div><div class="grid-row">
    <?php endif; ?>
    <div class="grid-item" onclick="document.location = '<?php echo $_product->getProductUrl() ?>'; return false;">
    	
                <?php // Product Image ?>
                <div class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(250, 250); ?>" width="250" height="250" alt="<?php echo $this->helper('awmobile')->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" title="<?php echo $this->helper('awmobile')->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                </div>
                <?php // Product description ?>
                <div class="product-shop">
                    <?php $simplePricesTax = ($this->helper('tax')->displayPriceIncludingTax() || $this->helper('tax')->displayBothPrices()); ?>
                    <?php $_minimalPriceValue = $_product->getMinimalPrice() ?>
                    <?php $_minimalPrice = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $simplePricesTax) ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->helper('awmobile')->stripTags($_product->getName(), null, true) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a>
                    <?php
                    if ($_product->getTypeId() == 'bundle'){
                        list($_minimalPrice, $_maximalPrice) = $_product->getPriceModel()->getPrices($_product);
                        $_price = $_minimalPrice;
                    } elseif ($_product->getTypeId() == 'grouped') {     
                        $_exclTax = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $includingTax = null);
                        $_inclTax = $this->helper('tax')->getPrice($_product, $_minimalPriceValue, $includingTax = true);                        
                        $_price = $_inclTax;
                        if (!$this->helper('tax')->displayPriceIncludingTax()) {
                            $_price = $_exclTax;
                        }                        
                    } else {
                        $_price = $_product->getFinalPrice();
                    } ?>
                    <?php echo $this->getPriceHtml($_product, true) ?>
                </div>   
</div>
<?php $i++; ?>
<?php endforeach; ?>
</div>
<div class="clear"></div>
</div>
</div>
<script type="text/javascript">
jQuery(window).load(function(){
	jQuery('.grid-row').each(function(e){
		if(jQuery(this).find('.grid-item:eq(0)').outerHeight()!=jQuery(this).find('.grid-item:eq(1)').outerHeight()) {
			var highestCol = Math.max(jQuery(this).find('.grid-item:eq(0)').outerHeight(),jQuery(this).find('.grid-item:eq(1)').outerHeight());
			jQuery(this).find('.grid-item').height(highestCol);
		}	
	});
});
</script>
<?php endif; ?>
<script type="text/javascript">
    decorateList('c-list', 'none-recursive');
    
    /* Redrawing of catalog list */
    var redrawList = function(){
        $j('ul.c-list div.description').each(function(index, element){
            var targetNode = $j(element.parentNode);
            var screenW = $j(element.parentNode.parentNode).width();
            var firstChildWidth = $j(element.parentNode.parentNode.select('.col-1')[0]).width();
            targetNode.width(screenW - firstChildWidth);
        });        
    };
    redrawList();
    $j(document).ready(function(){
        $j(document).bind('checkorientationchange', function(){
            redrawList();
        });
    });

    jQuery(function(){
    	jQuery('#layer-sort').click(function(e){
			if(jQuery(this).parent().hasClass('active')) {
				jQuery(this).parent().removeClass('active');
				jQuery('.nav-content-sort').hide();
			} else {
				jQuery(this).parent().addClass('active');
				jQuery('.nav-button-pager').removeClass('active');
				jQuery('.nav-content-pager').hide();
				jQuery('.nav-button-view').removeClass('active');
				jQuery('.nav-content-view').hide();
				jQuery('.nav-button-filter').removeClass('active');
				jQuery('.upper-toolbar .layered-nav').hide();
				jQuery('.nav-content-sort').show();
			}
			e.preventDefault();
		});
		jQuery('#layer-view').click(function(e){
			if(jQuery(this).parent().hasClass('active')) {
				jQuery(this).parent().removeClass('active');
				jQuery('.nav-content-view').hide();
			} else {
				jQuery(this).parent().addClass('active');
				jQuery('.nav-button-pager').removeClass('active');
				jQuery('.nav-content-pager').hide();
				jQuery('.nav-button-sort').removeClass('active');
				jQuery('.nav-content-sort').hide();
				jQuery('.nav-button-filter').removeClass('active');
				jQuery('.upper-toolbar .layered-nav').hide();
				jQuery('.nav-content-view').show();
			}
			e.preventDefault();
		});
		jQuery('#layer-page').click(function(e){
			if(jQuery(this).parent().hasClass('active')) {
				jQuery(this).parent().removeClass('active');
				jQuery('.nav-content-pager').hide();
			} else {
				jQuery(this).parent().addClass('active');
				jQuery('.nav-button-view').removeClass('active');
				jQuery('.nav-content-view').hide();
				jQuery('.nav-button-sort').removeClass('active');
				jQuery('.nav-content-sort').hide();
				jQuery('.nav-button-filter').removeClass('active');
				jQuery('.upper-toolbar .layered-nav').hide();
				jQuery('.nav-content-pager').show();
			}
			e.preventDefault();
		});
		jQuery('#layer-filter').click(function(e){
			if(jQuery(this).parent().hasClass('active')) {
				jQuery(this).parent().removeClass('active');
				jQuery('.upper-toolbar .layered-nav').hide();
			} else {
				jQuery(this).parent().addClass('active');
				jQuery('.nav-button-pager').removeClass('active');
				jQuery('.nav-content-pager').hide();
				jQuery('.nav-button-sort').removeClass('active');
				jQuery('.nav-content-sort').hide();
				jQuery('.nav-button-view').removeClass('active');
				jQuery('.nav-content-view').hide();
				jQuery('.upper-toolbar .layered-nav').show();
			}
			e.preventDefault();
		});
		jQuery('.narrow-by dt').click(function(e){
			if(jQuery(this).hasClass('active')) {
				jQuery(this).removeClass('active').next().hide();
			} else {
				jQuery(this).addClass('active').next().show();
			}
		});
    });
    function backToTop() {
    	jQuery('body,html').animate({scrollTop:0},800);
    	return false;
    }
    
</script>
<div class="bottom-toolbar">
	<?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>
