<select name='<?php echo $this->getFieldName()?>' id='<?php echo $this->getFieldId()?>' class='<?php echo $this->getFieldClass()?>' style='<?php echo $this->getFieldStyle()?>'>

<?php 				

foreach($this->getFieldOptions() as $i=>$option){
	$checked = false;
	if($option["checked"]){
		$checked = 'selected';
	}
	if(!empty($option["value"])){
		$contact = $this->getField()->getContactArray($option["value"]);
		if($contact){
?>

<option value="<?php echo $i?>" <?php echo $checked?>><?php echo $contact['name']?></option>

<?php
		
		}
	}
}

?>

</select>