<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<fieldset class="form-list">
    <ul id="payment_form_<?php echo $this->getMethodCode() ?>" style="display:none">
        <li>
            <div><label for="po_number"><?php echo $this->__('Purchase Order Number') ?> <span class="required">*</span></label></div>
            <div class="input-box">
                <input type="text" id="po_number" name="payment[po_number]" title="<?php echo $this->__("Purchase Order Number") ?>" class="required-entry input-text" value="<?php echo $this->htmlEscape($this->getInfoData('po_number')) ?>"/>
            </div>
        </li>
    </ul>
</fieldset>
