<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php 
/**
 * Mustishipping state
 * 
 * @see Mage_Checkout_Block_Multishipping_State
 */
?>
<center>
    <span class="checkout-progress-container">
    <ul class="checkout-progress" id="checkout-progress-state">
      <?php foreach ($this->getSteps() as $_step): ?>
            <li<?php if($_step->getIsActive()): ?> class="active"<?php endif ?>>
                <span>
                    <?php echo $_step->getLabel() ?>
                </span>
            </li>
      <?php endforeach; ?>
    </ul>        
    <div class="clear"></div>
    </span>
</center>

<script type="text/javascript">decorateGeneric($$('#checkout-progress-state li'), ['first','last']);</script>
