<ol>
<?php foreach ($this->getItems() as $_item):?>
    <li>
        <?php if ($_item->getIsCurrent()): ?>
            <span class="adj-nav-category-current"><?php echo $_item->getLabel() ?></span>
        <?php  else: ?>
            <a id="cat-<?php echo $_item->getValue()?>" href="<?php echo $this->htmlEscape($_item->getUrl()) ?>" class="adj-nav-category adj-nav-pad<?php echo $_item->getLevel()?>"><?php echo $_item->getLabel() ?></a>
            <?php if($_item->getCount()): ?>  (<?php echo $_item->getCount() ?>) <?php endif ?>
        <?php endif ?>
    </li>
<?php endforeach ?>
</ol>