<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
/* @var $this Mage_Reports_Block_Product_Viewed */
?>
<?php if ($_products = $this->getRecentlyViewedProducts()): ?>
<div class="box base-mini mini-product-view">
    <div class="head">
        <h4><span><?php echo $this->__('Recently Viewed Products') ?></span></h4>
    </div>
    <div class="content">
        <ol id="recently-viewed-items">
        <?php foreach ($_products as $_item): ?>
            <li><a href="<?php echo $this->getProductUrl($_item) ?>"><?php echo $this->helper('catalog/output')->productAttribute($_item, $_item->getName() , 'name') ?></a></li>
        <?php endforeach; ?>
        </ol>
    </div>
    <script type="text/javascript">
    decorateList('recently-viewed-items')
    </script>
</div>
<?php endif; ?>
