<style>
.developer {
	background: #FAFAFA;
	border: 1px solid #CCCCCC;
	margin-bottom: 10px;
	padding: 10px;
	height: auto;
}

.developer h3 {
	color: #444;
}

.contact-type {
	color: #EA7601;
	font-weight: bold;
}

.developer img {
	float: left;
}

.developer .info {
	background: #E7EFEF;
	padding: 5px 10px 0 5px;
	margin-left: 210px;
	height: 195px;
}
</style>

<div class="developer">
	<a href="http://www.ecommerceoffice.com/magento-menu/"
		target="_blank"><img
		src="http://magento16.dev/skin/frontend/base/default/ip_robots/menu_box.jpg"
		alt="www.ecommerceoffice.com">
	</a>
	<div class="info">
		<h3>MEGAMENU - Band new Magento navigation menu</h3>
Menu - is a key navigation element for customers on your website. It is particularly important that the menu would contain a maximum of all information, 
namely that which is needed by your potential customers. Alas, based on analysis of user behavior on large portals, the attention of given only for the first 
 10% - 20% of all categories of the store directories.<br>
The remaining elements are simply not visible to users and are not used.Shop can increase profits by changing the sitemenu - users should see all items of your catalog products immediately. It is necessary that information was 
available at the first click.
And this menu allows you to fully control/edit the store catalog displaying typ...
		 </p>

<a href="http://demo.ecommerceoffice.com/" target="_blank"><img src="http://magazento.com/promo/extension_demo.png" alt=""></a>
<a title="megamenu" href="https://www.magentocommerce.com/magento-connect/navigation-menu-megamenu.html" target="_blank"><img src="http://magazento.com/promo/extension_page.png" alt=""></a>
		<br><br><br><span class="contact-type">MagentoConnect:</span> 
		<a href="https://www.magentocommerce.com/magento-connect/developer/Magazento/" target="_blank"> click here to view all our extensions</a>
		<br>
	</div>
</div>
<div class="developer">
	<a href="http://www.ecommerceoffice.com/"
		target="_blank"><img
		src="http://magento16.dev/skin/frontend/base/default/ip_robots/promo.jpg"
		alt="www.ecommerceoffice.com">
	</a>
	<div class="info">
		<h3>PROFESSIONAL STORE DEVELOPMENT</h3>
		  As a company, we provide a wide range of services related to the e-shops development,
		 their design and installation as well as their configuration on Magento e-commerce 
		 platform.  There are no limits to creativity with us and Magento. 
		You will pay less to go live with our wide range of solutions and services!
		 </p>
		--------------------------------------------------------------------<br>
		<span class="contact-type">Website:</span> 
		<a href="http://www.ecommerceoffice.com/" target="_blank">www.ecommerceoffice.com</a> / 
		<a href="http://www.magazento.com/" target="_blank">www.magazento.com</a>
		<br>
		<span class="contact-type">E-mail:</span> volgodark@gmail.com /
		office.commerce@gmail.com<br>
		<span class="contact-type">Skype:</span> volgodark /
		<span class="contact-type">Phone:</span> +7 988024 1612 / +7 909389 2222
		<br>
		<span class="contact-type">Facebook:</span> <a
			href="http://www.facebook.com/ivan.proskuryakov" target="_blank">visit</a>
		/
		<span class="contact-type">LinkedIn:</span> <a
			href="http://www.linkedin.com/pub/ivan-proskuryakov/31/200/316"
			target="_blank">visit</a> <br>
	</div>
</div>