<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php $_item = $this->getItem()?>
<div class="cart-row" id="<?php echo $_item->getId() ?>">
	<div class="thumb">
		<?php if (in_array($_item->getProductId(),$loose_id)):?>
			<img src="<?php echo $this->getProductThumbnail(array('_secure' => true)); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>"  />
		<?php else: ?>
			<?php if ($_item->getProductId() == 31774):?>
				<img src="<?php echo $this->getProductThumbnail()->resize(180); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" width="180" />
			<?php else: ?>
				<a href="<?php echo $this->getProductUrl() ?>">
					<img src="<?php echo $this->getProductThumbnail()->resize(180); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" width="180" />
				</a>
			<?php endif; ?>
		<?php endif; ?>
	</div>
	<div class="info">
		<p><?php if ($this->hasProductUrl()):?>
        	<a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a>
        <?php else: ?>
        	<?php echo $this->htmlEscape($this->getProductName()) ?>
        <?php endif; ?></p>
        <?php if ($_item->getProductId() != 31774):?>
        <p class="sku"><?php echo $this->__('Stock #: ') ?><?php echo $_item->getSku() ?></p>
        <dl class="item-options">
        	<?php if ($_options = $this->getOptionList()):?>
	            <?php foreach ($_options as $_option) : ?>
	            <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
	            <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
	            <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
	                <?php if (isset($_formatedOptionValue['full_view'])): ?>
	                <div class="truncated_full_value">
	                    <dl class="item-options">
	                        <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
	                        <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
	                    </dl>
	                </div>
	                <?php endif; ?>
	            </dd>
	            <?php endforeach; ?>
            <?php endif;?>
            <dt><?php echo $this->__('Quantity') ?></dt>
            <dd><span class="edit-input-box"><input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" class="input-text qty" maxlength="8" /></span><span class="normal-input-box"><?php echo $this->getQty(); ?></span></dd>
        </dl>
        <?php endif; ?>
	</div>
	<div class="clear"></div>
	<div class="bottom-totals-items">
		<div class="action-buttons">
	        <a href="#" class="remove-cart" onclick="removeCartItem(<?php echo $_item->getId() ?>); return false;">
	            <?php echo $this->__('Remove'); ?>
	        </a>
	        <a href="#" class="edit-cart" onclick="editCartItem(<?php echo $_item->getId() ?>); return false;">
	            <?php echo $this->__('Edit'); ?>
	        </a>
        </div>
        <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
	        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	            <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
	        <?php else: ?>
	            <div class="cart-price">
	        <?php endif; ?>
				<?php echo $this->__('Subtotal'); ?>
	            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?>
	            <?php else: ?>
	                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
	            <?php endif; ?>
	
	        </div>
	        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
	
	            <div class="cart-tax-info" id="esubtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
	                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                    <small>
	                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
	                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
	                    <?php endforeach; ?>
	                    </small>
	                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
	                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
	                    <?php endforeach; ?>
	                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                    <small>
	                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
	                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
	                    <?php endforeach; ?>
	                    </small>
	                <?php endif; ?>
	            </div>
	
	            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                <div class="cart-tax-total" onclick="taxToggle('esubtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
	                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()+$_item->getWeeeTaxAppliedRowAmount()+$_item->getWeeeTaxRowDisposition()); ?></span>
	                </div>
	            <?php endif; ?>
	        <?php endif; ?>
	    <?php endif; ?>
	    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
	        <?php $_incl = $this->helper('checkout')->getSubtotalInclTax($_item); ?>
	        <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	            <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
	        <?php else: ?>
	            <div class="cart-price">
	        <?php endif; ?>
				<?php echo $this->__('Subtotal'); ?>
	            <?php if (Mage::helper('weee')->typeOfDisplay($_item, array(0, 1, 4), 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?>
	            <?php else: ?>
	                <?php echo $this->helper('checkout')->formatPrice($_incl-$_item->getWeeeTaxRowDisposition()) ?>
	            <?php endif; ?>
	            
	        </div>
	
	
	        <?php if (Mage::helper('weee')->getApplied($_item)): ?>
	
	            <div class="cart-tax-info" id="subtotal-item-tax-details<?php echo $_item->getId(); ?>" style="display: none;">
	                <?php if (Mage::helper('weee')->typeOfDisplay($_item, 1, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                    <small>
	                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
	                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount'],true,true); ?></span><br />
	                    <?php endforeach; ?>
	                    </small>
	                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
	                        <span class="nobr"><small><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></small></span><br />
	                    <?php endforeach; ?>
	                <?php elseif (Mage::helper('weee')->typeOfDisplay($_item, 4, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                    <small>
	                    <?php foreach (Mage::helper('weee')->getApplied($_item) as $tax): ?>
	                        <span class="nobr"><?php echo $tax['title']; ?>: <?php echo Mage::helper('checkout')->formatPrice($tax['row_amount_incl_tax'],true,true); ?></span><br />
	                    <?php endforeach; ?>
	                    </small>
	                <?php endif; ?>
	            </div>
	
	            <?php if (Mage::helper('weee')->typeOfDisplay($_item, 2, 'sales') && $_item->getWeeeTaxAppliedAmount()): ?>
	                <div class="cart-tax-total" onclick="taxToggle('subtotal-item-tax-details<?php echo $_item->getId(); ?>', this, 'cart-tax-total-expanded');">
	                    <span class="nobr"><?php echo Mage::helper('weee')->__('Total incl. tax'); ?>:<br /> <?php echo $this->helper('checkout')->formatPrice($_incl+$_item->getWeeeTaxAppliedRowAmount()); ?></span>
	                </div>
	            <?php endif; ?>
	        <?php endif; ?>
	    <?php endif; ?>
	</div>        
</div>