<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php echo $this->getChildHtml('items_before'); ?>
<div id="checkout-review-table-wrapper" class="bottom-space">
    <table cellspacing="0" class="shopping-cart checkout-review" id="checkout-review-table">
        <?php echo $this->getChildHtml('totals'); ?>
        <tbody>
        <?php foreach($this->getItems() as $_item): ?>
            <?php echo $this->getItemHtml($_item)?>
        <?php endforeach ?>
        </tbody>
    </table>
</div>
<script type="text/javascript">
    decorateTable('checkout-review-table');
    truncateOptions();
</script>
