<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="page-title">
    <h1><?php echo $this->__('Currency') ?></h1>
</div>
<p><?php echo $this->__('Your current currency is: %s', $currency->getCode()) ?></p>
<p><a href="<?php echo Mage::getBaseUrl() ?>"><?php echo $this->__('Continue &raquo;') ?></a></p>
