<table id="Table_01" width="950" height="431" border="0" cellpadding="0" cellspacing="0" style="margin-top:-30px; margin-left:-10px;"> 


<tr> 


<td colspan="3" rowspan="2"> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_01.jpg" width="407" height="269" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/header_main.jpg" width="1" height="231" alt=""></td> 

<td colspan="3"> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_03.jpg" width="542" height="231" alt=""></td> 

</tr> 

<tr> 

<td colspan="4"> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_04.jpg" width="543" height="38" alt=""></td> 

</tr> 

<tr> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_05.jpg" width="168" height="108" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_06.jpg" width="201" height="108" alt=""></td> 

<td colspan="3"> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_07.jpg" width="195" height="108" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_08.jpg" width="209" height="108" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_09.jpg" width="177" height="108" alt=""></td> 

</tr> 

<tr> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_10.jpg" width="168" height="28" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_11.jpg" width="201" height="28" alt=""></td> 

<td colspan="3"> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_12.jpg" width="195" height="28" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_13.jpg" width="209" height="28" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_14.jpg" width="177" height="28" alt=""></td> 

</tr> 

<tr> 

<td colspan="7"> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/Avianne2012Head_15.jpg" width="950" height="25" alt=""></td> 

</tr> 

<tr> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="168" height="1" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="201" height="1" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="38" height="1" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="1" height="1" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="156" height="1" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="209" height="1" alt=""></td> 

<td> 

<img src="http://www.avianneandco.com/store/skin/frontend/default/blue/homeimg/spacer.gif" width="177" height="1" alt=""></td> 

</tr> 



</table> 

