<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php foreach ($languages as $_code=>$_link): ?>
    <?php if($_link): ?>
        <a href="<?php echo $_link ?>"><img src="<?php echo $this->getSkinUrl('images/flag_<?php echo $_code ?>.gif') ?>" width="30" height="20" alt="<?php echo $_code ?>" /></a>
    <?php else: ?>
        <!--img src="<?php echo $this->getSkinUrl('images/flag_<?php echo $_code ?>.gif') ?>" width="30" height="20" alt="<?php echo $_code ?>"/-->
    <?php endif; ?>
<?php endforeach; ?>
