<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * Language switcher template
 *
 * @see Mage_Page_Block_Switch
 */

?>
<?php /*if(count($this->getStores())>1): ?>

    <select id="select-language" onchange="setLocation(this.value)">
    <?php foreach ($this->getStores() as $_lang): ?>
        <?php $_selected = ($_lang->getId()==$this->getCurrentStoreId()) ? 'selected="selected"' : '' ?>
        <option value="<?php echo $_lang->getCurrentUrl() ?>" <?php echo $_selected ?>><?php echo $this->htmlEscape($_lang->getName()) ?></option>
    <?php endforeach; ?>
    </select>
    <?php echo $this->getChildHtml('switcher_links'); ?>
<?php else: ?>
    <?php echo $this->getChildHtml('switcher_links'); ?>
<?php endif;*/ ?>

