<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="">
    <div class="head">
        <h5><?php echo $this->__('Newsletters') ?></h5>
        <a class="edit" href="<?php echo $this->getUrl('newsletter/manage') ?>"><img src="<?php echo $this->getSkinUrl('images/edit.gif') ?>" alt="<?php echo $this->__('Edit Newsletters') ?>" /></a>
    </div>
    <div class="content"><?php echo $this->__('You are currently subscribed to our newsletter.') ?></div>
</div>
