<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php 
    $_order  = $this->getOrder();
    $_source = $this->getSource();
    $_cards  = $this->getGiftCards();
?>
<?php if ($_cards):?>
<?php foreach ($_cards as $_card): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card (%s)', $_card->getCode()); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_card->getAmount()) ?></td>
</tr>
<?php endforeach; ?>
<?php elseif ($_source->getGiftCardsAmount()>0): ?>
<tr>
    <td <?php echo $this->getLabelProperties()?>>
        <?php echo Mage::helper('enterprise_giftcardaccount')->__('Gift Card'); ?>
    </td>
    <td <?php echo $this->getValueProperties()?>>-<?php echo $_order->formatPrice($_source->getGiftCardsAmount()) ?></td>
</tr>
<?php endif?>
