<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<p><?php echo $this->getMethod()->getTitle() ?>
<?php if($this->getInfo()->getAdditionalData()): ?>
    <?php if($this->getPayableTo()): ?><br /><?php echo $this->__('Make Check payable to: %s', $this->htmlEscape($this->getPayableTo())) ?><?php endif; ?>
    <?php if($this->getMailingAddress()): ?>
        <br /><?php echo Mage::helper('payment')->__('Send Check to:') ?>
        <br />
        <span class="checkmo-mailing-address">
            <?php echo nl2br($this->htmlEscape($this->getMailingAddress())) ?>
        </span>
    <?php endif; ?>
<?php endif; ?>
</p>
