<?php
/**
 * Amazon Diagnostics
 *
 * @category    Amazon
 * @package     Amazon_Diagnostics
 * @copyright   Copyright (c) 2015 Amazon.com
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/* @var $this Amazon_Payments_Block_Adminhtml_Diagnostics */
?>

<textarea id="amazon_diagnostics_result" cols="40" style="width:100%; font-family:monospace;" wrap="off" readonly="readonly"></textarea>
