<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * Products list Pagination
 *
 * @see Mage_Catalog_Block_Product_List_Toolbar_Pager
 */
?>
<ul>
<?php if ($this->canShowFirst()): ?>
    <li><a class="first" href="<?php echo $this->getFirstPageUrl() ?>"><?php echo $this->__('First Page'); ?></a></li>
<?php endif;?>
<?php foreach ($this->getFramePages() as $_page): ?>
    <?php if ($this->isPageCurrent($_page)): ?>
        <li class="current"><span><?php echo $this->__('Page'); ?> <?php echo $_page ?> <?php echo $this->__('of'); ?> <?php echo $this->getLastPageNum() ?></span></li>
    <?php else: ?>
        <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $this->__('Page'); ?> <?php echo $_page ?> <?php echo $this->__('of'); ?> <?php echo $this->getLastPageNum() ?></a></li>
    <?php endif;?>
<?php endforeach;?>
<?php if ($this->canShowLast()): ?>
  <li><a class="last" href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->__('Last Page'); ?></a><li>
<?php endif;?>
</ul>
