<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Points
 * @copyright  Copyright (c) 2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>


<div class="page-head">
    <h4><?php echo $this->getTitle() ?></h4>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="content">
<?php echo $this->getChildHtml('')?>
</div>

<div class="button-set">
    <p class="left">
        <a href="<?php echo $this->getUrl('customer/account/index')?>">
            <small>&laquo; </small>  <?php echo $this->__('Back') ?>
        </a>
    </p>
</div>
