<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div id="checkout-review-load" class="default-box bottom-space">
    <?php echo $this->getChildHtml('info') ?>
</div>
<div class="content">
	<div id="checkout-review-submit">
	    <?php if(Mage::getBlockSingleton('checkout/agreements')):?>
	    	<?php echo $this->getChildHtml('agreements') ?>
	    <?php endif; ?>
	    <span id="review-buttons-container" class="a-center">
			<a class="button button-blue-gradient" id="place-order-button" onclick="review.save();" href="javascript:return false;"><span><?php echo $this->__('Place Order') ?></span></a>
		</span>
			<br />
			<span id="review-please-wait" style="display:none;padding:0 7px;" class="opc-please-wait">
				<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Submitting order information...') ?> &nbsp;
			</span>
	    <script type="text/javascript">
	        var review = new Review('<?php echo $this->getUrl('checkout/onepage/saveOrder', array('form_key' => Mage::getSingleton('core/session')->getFormKey())) ?>', '<?php echo $this->getUrl('checkout/onepage/success') ?>', $('checkout-agreements'));
	    </script>
	</div>
</div>