<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<form id="co-shipping-method-form" action="">
<div class="inner-box">
    <div class="default-box" id="checkout-shipping-method-load">
        <?php echo $this->getChildHtml('available') ?>
    </div>
</div>
<script type="text/javascript">
    var shippingMethod = new ShippingMethod('co-shipping-method-form', "<?php echo $this->getUrl('checkout/onepage/saveShippingMethod') ?>");
</script>
<div id="onepage-checkout-shipping-method-additional-load">
<?php echo $this->getChildHtml('additional') ?>
</div>
<p class="notice"><?php echo $this->__('*Orders shipped to APO/FPO Addresses are sent via USPS.');?><br /><?php echo $this->__('Please allow 7-10 days for delivery.'); ?></p>
<p class="notice notice-2"><?php echo $this->__('**Orders may not be shipped to a PO box.');?><br /><?php echo $this->__('Please provide a physical address for signed delivery.'); ?></p>
</form>
    <div class="a-right bottom-space">
        <div class="framebutton">
            <span id="shipping-method-buttons-container">
                <button type="button" class="form-button right" onclick="shippingMethod.save();"><span><?php echo $this->__('Continue') ?></span></button>
                <br />
                <span id="shipping-method-please-wait" style="display:none;" class="opc-please-wait">
                    <img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" class="v-middle" alt="" /> &nbsp; <?php echo $this->__('Loading next step...') ?> &nbsp;
                </span>
            </span>
        </div>
  </div>

