<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if( ($_additional = $this->getAdditionalData()) && (Mage::getStoreConfig('awmobile/product_page/catalog_additional_data')) ): ?>
<div class="collateral-box attribute-specs">
    <div class="additional-info table-box" id="product-attribute-specs-table">
    <?php foreach ($_additional as $_data): ?>
    <div class="row">
        <div class="label col-left"><?php echo $_data['label'] ?></div>
        <div class="data col-right"><?php if($_data['label']=='Ring Size'): echo $this->__('# (ReSizable)'); else: echo $_data['value']; endif; ?></div>
    </div>
    <?php endforeach; ?>
    </div>
</div>
<?php endif;?>
