<?php
/**
* aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * aheadWorks does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * aheadWorks does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Productquestions
 * @version    1.5.0
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE-COMMUNITY.txt
 */
?>
<?php
$questions = $this->_collection;
?>
<h3><?php echo $this->__('Questions & Answers'); ?></h3>
    <?php if ($questions->getSize()): ?>
        <ul>
            <?php foreach ($questions->getItems() as $q): ?>
            	<li><?php echo $this->__('Q - %s',nl2br(htmlentities($q->getQuestionText(), null, 'UTF-8'))); ?></li>
				<li><?php echo $this->__('A - %s',AW_Productquestions_Helper_Data::parseURLsIntoLinks($q->getQuestionReplyText())); ?></li>
				<?php break; ?>
            <?php endforeach; ?> 
        </ul>
    <?php else: ?>
        <p><?php echo $this->__('No questions asked yet'); ?></p>
    <?php endif; ?>
<?php echo $this->getChildHtml('questions-summary'); ?>
