<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php if($this->getItems()->getSize()): ?>
<div class="box base-mini cross-sell">
    <div class="head">
        <h4><span><?php echo $this->__('Cross-sell Products') ?></span></h4>
    </div>
    <ol id="cross-sell-products">
     <?php foreach($this->getItems() as $_item): ?>
        <li>
            <div class="product-images">
                <a href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(38) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="38" height="38" /></a>
            </div>
            <div class="product-details">
                <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                <?php echo $this->helper('catalog/product')->getPriceHtml($_item) ?>
                <a href="<?php echo $this->getAddToCartUrl($_item) ?>"><?php echo $this->__('Add to Cart') ?></a>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('cross-sell-products')</script>
</div>
<?php endif ?>
