<?php
/**
 * Login with Amazon
 *
 * @category    Amazon
 * @package     Amazon_Payments
 * @copyright   Copyright (c) 2014 Amazon.com
 * @license     http://opensource.org/licenses/Apache-2.0  Apache License, Version 2.0
 */
?>


<script type="text/javascript">
function amazonLogout() {
    amazon.Login.logout();
    document.cookie = "amazon_Login_accessToken=; expires=Thu, 01 Jan 1970 00:00:00 GMT";
}
window.onAmazonLoginReady = amazonLogout;
</script>

<script type='text/javascript' src='<?php echo $this->getWidgetsUrl(); ?>'></script>

