<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

/**
 * @see Enterprise_GiftCardAccount_Block_Account_Redeem
 */
?>
<?php if ($this->canRedeem()): ?>
    <div class="account-block account-balance">
        <h4 class="legend"><?php echo Mage::helper('enterprise_giftcardaccount')->__('Redeem Gift Card'); ?></h4>
        <p><?php echo Mage::helper('enterprise_giftcardaccount')->__('Have a gift card? <a href="%s">Click here</a> to redeem it.', Mage::getUrl('enterprise_giftcardaccount/customer')); ?></p>
    </div>
<?php endif; ?>
