<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<?php
/**
 * @see Enterprise_Invitation_Block_Customer_List
 */
?>
<div class="page-head">
    <h2><?php echo Mage::helper('enterprise_invitation')->__('My Invitations'); ?></h2>
</div>
<div id="messages"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php echo $this->getChildHtml('invitations_table'); ?>
<br />