<div class="content-header">
    <table cellspacing="0" class="grid-header">
        <tr>
            <td><h3><?=$this->__('Import/Export product ranks')?></h3></td>
            <td class="a-right">
            	<button onclick="setLocation('<?php echo $this->getUrl('*/*/export'); ?>')" class="scalable" type="button"><span>Export ranks</span></button>
                <button onclick="editForm.submit()" class="scalable save" type="button"><span>Submit form</span></button>
            </td>
        </tr>
    </table>
</div>
<div class="entry-edit">
    <form id="edit_form" name="edit_form" enctype="multipart/form-data" method="post" action="<?=$this->getUrl('*/*/post')?>" >
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <h4 class="icon-head head-edit-form fieldset-legend"><?=$this->__('Import product ranks')?></h4>
        <fieldset id="my-fieldset">
            <table cellspacing="0" class="form-list">
                <tr>
                    <td class="label"><?=$this->__('Select file to upload')?> <span class="required">*</span></td>
                    <td class="input-ele"><input class="input-text required-entry" type="file" name="rank" /></td>
                </tr>
            </table>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var editForm = new varienForm('edit_form');
</script>