<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<h3 class="product-name"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->htmlEscape($this->getProductName()) ?></a></h3>
<!-- item custom options -->
<?php if ($_options = $this->getOptionList()):?>
<dl class="item-options">
    <?php foreach ($_options as $_option) : ?>
    <?php $_formatedOptionValue = $this->getFormatedOptionValue($_option) ?>
    <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
    <dd<?php if (isset($_formatedOptionValue['full_view'])): ?> class="truncated"<?php endif; ?>><?php echo $_formatedOptionValue['value'] ?>
        <?php if (isset($_formatedOptionValue['full_view'])): ?>
        <div class="truncated_full_value">
            <dl class="item-options">
                <dt><?php echo $this->htmlEscape($_option['label']) ?></dt>
                <dd><?php echo $_formatedOptionValue['full_view'] ?></dd>
            </dl>
        </div>
        <?php endif; ?>
    </dd>
    <?php endforeach; ?>
</dl>
<?php endif;?>
<!-- / -->
    <!-- downloadable -->
    <?php if ($links = $this->getLinks()): ?>
    <dl class="item-options">
        <dt><?php echo $this->getLinksTitle() ?></dt>
        <?php foreach ($links as $link): ?>
            <dd><?php echo $link->getTitle() ?></dd>
        <?php endforeach; ?>
    </dl>
    <?php endif; ?>
    <!-- EOF downloadable -->
