<div class="box base-mini new-albums">
    <div class="head">
        <h4><?php echo $this->__('Featured Album') ?></h4>
    </div>

	<?php 	$featured_albums = $this->getFeatureAlbums(); ?>

	<ul>
	<?php	foreach ($featured_albums as $item){?>
			<li>				
				<a href="<?php echo $item->getUrlRewrite()?>" alt="<?php echo $item->getTitle() ?>" ><img src="<?php echo $this->helper('gallery/image')->init($item->getFilename())->resize(85, 85) ?>"/></a>
			</li>		
	<?php } ?>
	</ul>	

	<div class='view-all'><a href="<?php echo $this->getUrl('gallery') ?>">View all</a></div>	
</div>
