<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Mobile
 * @copyright  Copyright (c) 2010-2011 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */
?>
<div class="page-head"><h1><?php echo $this->__('Forgot Your Password?') ?></h1></div>
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('social_line')->toHtml(); ?>
<div class="login-box">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">
        <fieldset>
            <legend><?php echo $this->__('Retrieve your password here') ?></legend>
            <?php echo $this->__('Please enter your email below and we\'ll send you a new password.') ?>
            <ul class="form-list" style="margin-top:5px;">
                <li>
                        <div>
                            <label for="email_address"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label>
                        </div>
                        <div class="input-box">
                            <input name="email" alt="email" type="text" id="email_address" class="required-entry validate-email input-text" value="<?php echo $this->htmlEscape($this->getEmailValue()) ?>" />
                        </div>
                </li>
            </ul>
            <p class="a-right required"><?php echo $this->__('* Required Fields') ?></p>
            <div class="a-center">
                 <button type="submit" class="form-button right"><span><?php echo $this->__('Submit') ?></span></button><br />
            </div>
        </fieldset>
    </form>
</div>
<script type="text/javascript">
    var dataForm = new VarienForm('form-validate', true);
</script>
