<script>
			var BLANK_IMG = 'http://127.0.0.1/magento-1.4.0.1/skin/frontend/default/default/gallery/images/colorbox/overlay.png';
			
			jQuery(document).ready(function(){
				//Examples of how to assign the ColorBox event to elements
				jQuery("a[rel='example1']").colorbox();
				});
</script>
<p><a href="http://127.0.0.1/magento-1.4.0.1/media/gallery/Sunset1.jpg" rel="example1" title="Me and my grandfather on the Ohoopee.">Grouped Photo 1</a></p>