<script type="text/javascript">
function pageload(hash) {
	// alert("pageload: " + hash);
	// hash doesn't contain the first # character.
	if(hash) {
		// restore ajax loaded state
		if(jQuery.browser.msie) {
			// jquery's $.load() function does't work when hash include special characters like aao.
			hash = encodeURIComponent(hash);
		}
		document.getElementById('loading').style.display = 'block';
		jQuery("#photo-view-page").load('<?php echo $this->getUrl();?>' + hash,
				function(){
					document.getElementById('loading').style.display = 'none';
					//reload breadcrumbs
					jQuery(".breadcrumbs").load('<?php echo $this->getUrl("gallery/p/getBreadcrumb");?>id/'+document.getElementById('gallery_id').value);
				});
	} else {
		// start page
		//$("#photo-view-page").empty();
		//window.location ="<?php echo $this->getUrl("gallery")?>";
		
	}
}

jQuery(document).ready(function(){
	// Initialize history plugin.
	// The callback is called at once by present location.hash. 
	jQuery.historyInit(pageload);
});

</script>
<div class="loading" id="loading" style="display: none;"  >Loading ... </div>
<div id="photo-view-page">

</div>
